name: Deploy Frontend

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Run "npm ci"
        run: npm ci

      - name: Run "npm run build"
        run: npm run build
