name: "Terraform Plan/Apply"

on:
  pull_request:
    branches: main
    types: synchronize
    
  push:
    branches: infrastucture

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Terraform init/plan"
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      container_name: ${{secrets.AZURE_CONTAINER_NAME}}
      account_name: ${{secrets.AZURE_ACCOUNT_NAME}}
      key: ${{secrets.AZURE_STATE_KEY}}

    defaults:
      run:
        working-directory: ./terraform/app

    steps:
      - uses: actions/checkout@v4

      - name: "AZ CI login"
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Run terraform init"
        run: |
         terraform init \
         -backend-config="container_name=$container_name" \
         -backend-config="storage_account_name=$account_name" \
         -backend-config="resource_group_name=zupi-terraform-state" \
         -backend-config="key=$key"

      - name: "Run terraform validate"
        run: terraform validate

      - name: "Run terraform plan"
        run: |
         terraform plan \
         -var="location=southafricanorth" \
         -var="rg-name=zupi-terraform-state"

  terraform-apply:
    name: "Terraform apply"
    needs: terraform-plan
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
        ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
        ARM_CONTAINER_NAME: ${{secrets.AZURE_CONTAINER_NAME}}
        ARM_STORAGE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
        ARM_ACCESS_KEY: ${{secrets.AZURE_STATE_KEY}}
        ARM_RESOURCE_GROUP_NAME: zupi-terraform-state

    defaults:
      run:
        working-directory: ./terraform/app

    steps:
      - uses: actions/checkout@v4

      - name: "AZ CI login"
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Run terraform init"
        run: |
         terraform init

      - name: "Run terraform apply"
        run: |
         terraform apply \
         -var="location=southafricanorth" \
         -var="rg-name=zupi-terraform-state" \
         -auto-approve
