name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  container_name: ${{secrets.AZURE_CONTAINER_NAME}}
  account_name: ${{secrets.AZURE_ACCOUNT_NAME}}
  key: ${{secrets.AZURE_STATE_KEY}}

jobs:
  terraform-plan-destroy:
    name: "Terraform plan -destroy/ apply -destroy"
    runs-on: ubuntu-latest
    continue-on-error: false
    
    defaults:
      run:
        working-directory: ./terraform/app

    steps:
      - uses: actions/checkout@v4

      - name: "AZ CI login"
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Run terraform init
        run: |
          terraform init \
          -backend-config="container_name=$container_name" \
          -backend-config="storage_account_name=$account_name" \
          -backend-config="resource_group_name=$rg-name" \
          -backend-config="key=$key"

      - name: "Run plan -destroy"
        run: terraform plan -destroy
      
      - name: "Run terraform apply -destroy"
        run: terraform apply -destroy -auto-approve
