name: "Terraform Plan/Apply"

on:
  pull_request:
    branches: main
    types: synchronize
    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: "Terraform init/plan"
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      TF-VAR_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      TF-VAR_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      TF_VAR_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      TF_VAR_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      container_name: ${{secrets.AZURE_CONTAINER_NAME}}
      account_name: ${{secrets.AZURE_ACCOUNT_NAME}}
      key: ${{secrets.AZURE_STATE_KEY}}

    defaults:
      run:
        working-directory: ./terraform/app

    steps:
      - uses: actions/checkout@v4

      - name: "AZ CI login"
        uses: azure/login@v2
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: "Run terraform init"
        run: terraform init -backend-config="container_name=$container_name" -backend-config="storage_account_name=$account_name" -backend-config="key=$key"

      - name: "Run terraform Plan"
        run: terraform plan -backend-config="container_name=$container_name" -backend-config="storage_account_name=$account_name" -backend-config="key=$key"
#   terraform-apply:
#     name: "Terraform apply"
#     needs: terraform-plan
#     runs-on: ubuntu-latest
#     env:
#         TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
#         TF_VAR_tenant_id: ${{secrets.AZURE_TENANT_ID}}
#         TF_VAR_client_id: ${{secrets.AZURE_CLIENT_ID}}

#     defaults:
#       run:
#         working-directory: ./app

#     steps:
#       - uses: actions/checkout@v4

#       - name: "AZ CI login"
#         uses: azure/login@v2
#         with:
#           client-id: ${{secrets.AZURE_CLIENT_ID}}
#           tenant-id: ${{secrets.AZURE_TENANT_ID}}
#           subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

#       - name: "Setup Terraform"
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_wrapper: false

#       - name: "Initialse terraform"
#         run: terraform init \ -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \ -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \ -backend-config="key=$TF_STATE_KEY"

#       - name: "Run terraform apply"
#         run: terraform apply -auto-approve
