trigger:
  branches:
    include:
      - "*"
      - main

variables:
  ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(AZURE_TENANT_ID)
  ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
  container_name: $(AZURE_CONTAINER_NAME)
  account_name: $(AZURE_ACCOUNT_NAME)
  key: $(AZURE_STATE_KEY)
  location: southafricanorth
  rg_name: zupi-terraform-state

pool:
  vmImage: ubuntu-latest

jobs:
  - job: terraform_plan
    displayName: "Terraform Plan"

    steps:
      - script: |
          echo Hello, world!!!
          echo I am Lesedi.
        displayName: Run Hello world
