trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ./terraform/app/*
      - ./azure-pipelines/terraform-apply.yml

variables:
  - group: zupi-infrastructure

pool:
  vmImage: ubuntu-latest

jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - script: |
          az login --service-principal \
          --username $(lib-client-id) \
          --password $(lib-sp-password) \
          --tenant $(lib-tenant-id)
        workingDirectory: ./terraform/app
        displayName: Run "az login"
        
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest
        displayName: Terraform Installer

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(lib-storage-account-name)" \
          -backend-config="container_name=$(lib-container-name)" \
          -backend-config="key=$(lib-key)" \
          -backend-config="access_key=$(lib-access-key)"
        workingDirectory: ./terraform/app
        displayName: Run "terraform init"
        
      - script: |
          terraform plan -input=false \
          -var="location=$(lib-location)" \
          -var="rg-name=$(lib-rg-name)"
        workingDirectory: ./terraform/app
        displayName: Run "terraform plan"
        
  - job: Approval
    displayName: Manual Approval
    dependsOn: TerraformPlan
    pool: server
    steps:
      - task: ManualValidation@1
        displayName: Manual Validation
        timeoutInMinutes: 2
        inputs:
          notifyUsers: molemilesedi@gmail.com
          instructions: Please review the Terraform plan and approve to proceed with apply.
          onTimeout: reject
  
  - job: TerraformApply
    dependsOn: Approval
    condition: succeeded()
    displayName: Terraform Apply
    steps:
      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(lib-storage-account-name)" \
          -backend-config="container_name=$(lib-container-name)" \
          -backend-config="key=$(lib-key)" \
          -backend-config="access_key=$(lib-access-key)"
        workingDirectory: ./terraform/app
        displayName: Run "terraform init"

      - script: |
          terraform apply -auto-approve \
          -var="location=$(lib-location)" \
          -var="rg-name=$(lib-rg-name)"
        workingDirectory: ./terraform/app
        displayName: Run "terraform apply"