trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  key: "zupi.tfstate"
  
jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest
        displayName: Terraform Installer
        
      - task: AzureCLI@2
        inputs:
          azureSubscription: zupi-sp
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo Logging in to Azure CLI

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(storage-account-name)" \
          -backend-config="container_name=$(container-name)" \
          -backend-config="key=$(key)" \
          -backend-config="access_key=$(access-key)"
        displayName: Run "terraform init"
        workingDirectory: ./terraform/app
        
      - script: |
          terraform plan -input=false \
          -var="location=$(location)" \
          -var="rg-name=$(rg-name)"
        displayName: Run "terraform plan"
        workingDirectory: ./terraform/app