trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  key: "zupi.tfstate"
  
jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest
        displayName: Terraform Installer"

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(storage-account-name)" \
          -backend-config="container_name=$(container-name)" \
          -backend-config="key=$(key)" \
          -backend-config="access_key=$(access-key)" \
          -backend-config="tenant_id=f147f402-9ef8-49f2-9771-1add3815651e"
        displayName: Run "terraform init"
        workingDirectory: ./terraform/app
        
      - script: |
          terraform plan -input=false \
          -var="location=$(location)" \
          -var="rg-name=$(rg-name)"
        displayName: Run "terraform plan"
        workingDirectory: ./terraform/app