trigger:
  branches:
    exclude:
      - main
  paths:
    include:
      - ./terraform/app/*

pool:
  vmImage: ubuntu-latest
  
jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - script: |
          az login --service-principal \
          --username $(lib-client-id) \
          --password $(lib-sp-password) \
          --tenant $(lib-tenant-id)
        displayName: Run "az login"
        workingDirectory: ./terraform/app

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest
        displayName: Terraform Installer

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(lib-storage-account-name)" \
          -backend-config="container_name=$(lib-container-name)" \
          -backend-config="key=$(lib-key)" \
          -backend-config="access_key=$(lib-access-key)"
        displayName: Run "terraform init"
        workingDirectory: ./terraform/app
        
      - script: |
          terraform plan -input=false \
          -var="location=$(lib-location)" \
          -var="rg-name=$(lib-rg-name)"
        displayName: Run "terraform plan"
        workingDirectory: ./terraform/app