# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

variables:
  container_name: terraform-state
  storage_account: zupitfstate
  backend_rg_name: zupi-terraform-state
  rg-name: zupi-site
  key: zupi.tfstate
  location: southafricanorth

pool:
  vmImage: ubuntu-latest

jobs:
  - job: terraform_init
    steps:
      - checkout: self

      - script: |
          terraform init \
          -backend-config="container_name=$(container_name)" \
          -backend-config="storage_account_name=$(storage_account)" \
          -backend-config="resource_group_name=$(backend_rg_name)" \
          -backend-config="key=$(key)"
        workingDirectory: ./terraform/app
        displayName: Terraform Init
        
      - script: terraform validate
        displayName: Run Terraform Validate

  - job: terraform_plan
    dependsOn: terraform_init
    
    steps:
      - checkout: self

      - script: |
          terraform plan \
          -var="location=$(location)"
          -var="rg-name=$(rg-name)"

