# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: terraform_init
    steps:
      - checkout: self

      - task: AzureCLI@2
        inputs:
          azureSubscription: devops-sp
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
            echo Logged into Azure CLI

      - script: |
          terraform init \
          -backend-config="container_name=$(CONTAINER-NAME)" \
          -backend-config="storage_account_name=$(STORAGE-ACCOUNT)" \
          -backend-config="resource_group_name=$(BACKEND-RG-NAME)" \
          -backend-config="key=$(KEY)"
        env:
          ARM_CLIENT_ID: $(servicePrincipalId)
          ARM_CLIENT_SECRET: $(servicePrincipalKey)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_TENANT_ID: $(tenantId)
        workingDirectory: ./terraform/app
        displayName: Terraform Init
        
      - script: terraform validate
        displayName: Run Terraform Validate

  - job: terraform_plan
    dependsOn: terraform_init
    
    steps:
      - checkout: self

      - script: |
          terraform plan \
          -var="location=$(LOCATION)"
          -var="rg-name=$(RG-NAME)"
        env:
          ARM_CLIENT_ID: $(servicePrincipalId)
          ARM_CLIENT_SECRET: $(servicePrincipalKey)
          ARM_SUBSCRIPTION_ID: $(subscriptionId)
          ARM_TENANT_ID: $(tenantId)