trigger:
  branches:
    include:
      - main
      - azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  key: "zupi.tfstate"
  
jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(storage-account-name)" \
          -backend-config="container_name=$(container-name)" \
          -backend-config="key=$(key)" \
          -backend-config="resource_group_name=zupi-terraform-state" \
          -backend-config="subscription_id=ccd5d48d-3f68-4c17-9c04-2497adee6f88" \
          -backend-config="tenant_id=f147f402-9ef8-49f2-9771-1add3815651e" \
          -backend-config="client-id=ff060f2f-a64a-4ff1-b88d-ecdff1f588dc" \
          -backend-config="client_secret=$(access-key)"
        displayName: Run "terraform init"
        workingDirectory: ./terraform/app
        
      - script: |
          terraform plan -input=false \
          -var="location=$(location)" \
          -var="rg-name=$(rg-name)"
        displayName: Run "terraform plan"
        workingDirectory: ./terraform/app