trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest
  
jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: latest

      - script: |
          terraform init -input=false \
          -backend-config="storage_account_name=$(storage-account-name)" \
          -backend-config="container_name=$(container-name)" \
          -backend-config="key=$(key)" \
          -backend-config="access_key=$(access-key)"
        displayName: Run "terraform init"
        
      - script: |
          terraform plan -input=false \
          -var="location=$(location)" \
          -var="rg-name=$(rg-name)"
        displayName: Run "terraform plan"